export * from './author.interface';
export * from './book.interface';
export * from './genre.interface';
export * from './list-api-view.interface';
export * from './option.interface';
export * from './overall-statistics.interface';
export * from './search-options.interface';
export * from './sort-options.interace';
export * from './table-item-action.interface';
